import type { Metadata } from "next";
import Link from "next/link";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import { getShopTaxonomy } from "@/lib/supabase";

export const metadata: Metadata = {
  title: "Toxome | Privacy Policy",
  description:
    "Toxome LLC's Privacy Policy governing the collection, use, and disclosure of personal data across the Toxome website, iOS application, and browser extension.",
  alternates: { canonical: "/privacy" },
};

const LAST_UPDATED = "June 9, 2026";

export default async function PrivacyPage() {
  const taxonomy = await getShopTaxonomy();
  return (
    <>
      <Nav taxonomy={taxonomy} />
      <main
        style={{
          background: "var(--cream)",
          minHeight: "100vh",
          paddingTop: 88,
          paddingBottom: 120,
        }}
      >
        <article
          style={{
            maxWidth: 720,
            margin: "0 auto",
            padding: "0 32px",
            color: "var(--ink)",
            // Legal text renders in natural case (overriding the site-wide
            // lowercase rule) so defined terms and statutory references read
            // correctly.
            textTransform: "none",
          }}
        >
          <Eyebrow>privacy policy</Eyebrow>
          <Title>Privacy Policy</Title>
          <UpdatedLine>Last updated {LAST_UPDATED}</UpdatedLine>

          <Intro>
            This Privacy Policy (the &ldquo;Policy&rdquo;) describes how Toxome
            LLC, a New York limited liability company (&ldquo;Toxome,&rdquo;
            &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;), collects,
            uses, discloses, and otherwise processes personal data in connection
            with the website located at{" "}
            <a href="https://toxome.app">toxome.app</a> (the &ldquo;Site&rdquo;),
            the Toxome iOS application (the &ldquo;App&rdquo;), and the Toxome
            browser extension (the &ldquo;Extension,&rdquo; and together with the
            Site and the App, the &ldquo;Services&rdquo;).
          </Intro>

          <Intro>
            This Policy forms part of, and should be read together with, our{" "}
            <Link href="/terms">Terms of Use</Link>. By accessing or using the
            Services, you acknowledge that you have read and understood this
            Policy. Capitalized terms used but not defined in this Policy have
            the meanings given to them in the Terms of Use.
          </Intro>

          <H2 id="controller">1. Data Controller</H2>
          <P>
            For the purposes of the EU General Data Protection Regulation
            (Regulation (EU) 2016/679) (the &ldquo;GDPR&rdquo;) and the UK GDPR,
            the data controller responsible for your personal data is Toxome
            LLC, a New York limited liability company. Our contact details are
            set out in Section 13 (Contact) below. Toxome has not appointed a
            data protection officer, as it is not required to do so under
            Article 37 of the GDPR.
          </P>

          <H2 id="data-we-collect">2. Personal Data We Collect</H2>
          <P>We collect the following categories of personal data.</P>
          <H3>2.1 Account Data</H3>
          <P>
            When you register for an account through the Site or the App, we
            collect your email address and, where you provide them, your display
            name and profile photograph. Authentication is performed by Firebase
            Authentication, a service provided by Google LLC. We use this data to
            authenticate you, to associate your activity across the Services, and
            to send you transactional communications, including sign-in links and
            material notices concerning your account or the Services.
          </P>
          <H3>2.2 Service Data</H3>
          <P>
            When you use the App to scan a garment label, we collect and store
            the photograph of the label, the fibre composition extracted from
            it, the brand and category identified, and the corresponding Toxome
            Rating. Scans you save to your closet are retained in your account
            until you delete them. On the Site, we store the items you save to
            your wishlist and the filters you apply when browsing. We receive
            your subscription status from Apple, via RevenueCat, in order to
            determine your entitlement to premium features. During onboarding in
            the App, you may elect to provide preference information (including
            concerns, gender, budget, and focus areas), which we use to
            personalize the Services and which you may amend or delete at any
            time.
          </P>
          <H3>2.3 Technical and Analytics Data</H3>
          <P>
            We collect technical information generated by your use of the
            Services, including device type, browser type, approximate location
            derived from your IP address, and the pages or screens you access.
            The Services use a single first-party analytics identifier, stored on
            your device, to distinguish visits within our own aggregated
            reporting. We do not employ third-party advertising trackers and do
            not engage in cross-site tracking. The processing of this analytics
            identifier is subject to the consent requirements described in
            Section 5 (Cookies and Similar Technologies).
          </P>
          <H3>2.4 Extension Data</H3>
          <P>
            The Extension identifies the fibre composition, product name, brand,
            and image on clothing retail pages you visit, solely in order to
            display a garment score on the page before you. The Extension
            operates only on pages that disclose a fibre composition and remains
            inactive on all other pages. It does not read your browsing history,
            monitor the sites you visit, or construct a profile of you. Scoring
            is performed locally within the Extension, on your device; product
            information is transmitted to Toxome only where you elect to save an
            item to your wishlist or closet, in which case the product name,
            brand, image, link, and score are stored in your account.
            Authentication within the Extension uses Firebase, and your session
            is stored locally in the browser&apos;s extension storage.
          </P>

          <H2 id="legal-basis">3. Legal Bases for Processing</H2>
          <P>
            Where the GDPR or the UK GDPR applies, we process your personal data
            on the following legal bases:
          </P>
          <Ul>
            <li>
              <strong>Performance of a contract</strong> (Article 6(1)(b)): to
              create and administer your account, authenticate you, store your
              closet and wishlist, and provide the premium features for which you
              have subscribed.
            </li>
            <li>
              <strong>Legitimate interests</strong> (Article 6(1)(f)): to
              maintain the security and integrity of the Services, prevent abuse,
              and analyse aggregated usage in order to operate and improve the
              Services. We have determined that these interests are not
              overridden by your rights and freedoms, and we limit such
              processing to data that is minimal and non-advertising in nature.
            </li>
            <li>
              <strong>Consent</strong> (Article 6(1)(a)): to store the
              first-party analytics identifier on your device where required by
              applicable law, and to send marketing communications. You may
              withdraw your consent at any time, without affecting the lawfulness
              of processing carried out prior to such withdrawal.
            </li>
            <li>
              <strong>Compliance with a legal obligation</strong> (Article
              6(1)(c)): to retain records as required by law and to respond to
              lawful requests from public authorities.
            </li>
          </Ul>

          <H2 id="how-we-use">4. Purposes of Processing</H2>
          <P>We process personal data in order to:</P>
          <Ul>
            <li>
              operate and maintain the Services, including displaying your closet
              and wishlist and authenticating you;
            </li>
            <li>
              personalize the Services, including by recommending lower-risk
              alternatives in categories where your closet is assessed as higher
              risk;
            </li>
            <li>
              process subscription transactions through Apple and RevenueCat;
            </li>
            <li>
              send transactional communications, and marketing communications
              only where you have opted in;
            </li>
            <li>
              analyse de-identified, aggregated trends in order to improve and
              develop the Services; and
            </li>
            <li>
              comply with applicable law and protect the rights, property, and
              safety of Toxome and its users.
            </li>
          </Ul>
          <P>We do not sell your personal data.</P>

          <H2 id="cookies">5. Cookies and Similar Technologies</H2>
          <P>
            The Site uses strictly necessary cookies to maintain your
            authenticated session. The Site also uses a single first-party
            analytics identifier, stored in your browser, to distinguish visits
            within our own aggregated reporting; this identifier is not an
            advertising tracker, is not shared with third parties, and is not
            used for cross-site tracking. Where you access the Services from the
            European Economic Area or the United Kingdom, we obtain your consent
            before storing the analytics identifier on your device, in accordance
            with applicable ePrivacy laws; where you access the Services from
            other jurisdictions, the identifier is set without a prior consent
            requirement, consistent with applicable law. The App relies on
            standard identifiers provided by Apple and governed by Apple&apos;s
            App Tracking Transparency framework; we do not request tracking
            permission, as we do not require it.
          </P>

          <H2 id="who-we-share-with">6. Recipients and Disclosures</H2>
          <P>
            We do not sell your personal data. We disclose personal data only to
            the service providers that enable us to operate the Services, and
            only to the extent necessary for them to perform their functions:
          </P>
          <Ul>
            <li>
              <strong>Firebase (Google LLC)</strong>: authentication and storage
              of your closet, wishlist, and uploaded photographs.
            </li>
            <li>
              <strong>Supabase</strong>: hosting of our product catalogue. No
              user account is maintained with this provider; it serves only the
              catalogue data presented on the Site.
            </li>
            <li>
              <strong>RevenueCat and the Apple App Store</strong>: subscription
              management and payment processing. We do not receive your payment
              card details, which are processed by Apple.
            </li>
            <li>
              <strong>Vercel Inc.</strong>: hosting of the Site, including the
              handling of server request logs.
            </li>
            <li>
              <strong>Affiliate partners</strong>: where you select a link to a
              third-party brand, we direct you to that brand&apos;s website.
              Certain links contain an affiliate code by which we may earn a
              commission. We do not disclose your account or closet data to such
              brands; they receive only the fact that the referral originated
              from Toxome. We additionally maintain our own aggregated record of
              the products and brands viewed and clicked, associated with a
              random device identifier and not with your name or email address.
              This record is retained within Toxome and is not sold or disclosed
              to advertisers.
            </li>
            <li>
              <strong>Public authorities and other parties</strong>: where we
              receive a valid legal request, or where disclosure is necessary to
              comply with applicable law, enforce our Terms of Use, or protect
              the rights, property, or safety of Toxome or others.
            </li>
          </Ul>

          <H2 id="retention">7. Data Retention</H2>
          <P>
            We retain personal data for as long as your account remains active or
            as necessary to provide the Services. Following a request to delete
            your account, we will delete your account and associated personal
            data within thirty (30) days, except where retention is required to
            comply with a legal obligation (for example, transaction records) or
            to establish, exercise, or defend legal claims. Aggregated and
            de-identified data, which cannot reasonably be attributed to you, may
            be retained without time limit.
          </P>

          <H2 id="international">8. International Transfers</H2>
          <P>
            Our service providers store data in data centres located in the
            United States. If you access the Services from outside the United
            States, your personal data will be transferred to, and processed in,
            the United States. Where personal data is transferred from the
            European Economic Area or the United Kingdom, we rely on the European
            Commission&apos;s Standard Contractual Clauses (and, for transfers
            from the United Kingdom, the UK International Data Transfer Addendum),
            together with our providers&apos; data processing agreements, as the
            safeguard for such transfers, in accordance with applicable law.
          </P>

          <H2 id="your-rights">9. Your Rights</H2>
          <P>
            Subject to applicable law, you may have the right to access, rectify,
            erase, restrict, or object to the processing of your personal data,
            the right to data portability, and the right to withdraw consent
            where processing is based on consent. You may exercise these rights,
            and those set out below, by emailing{" "}
            <a href="mailto:nyah@toxome.app">nyah@toxome.app</a> from the email
            address associated with your account:
          </P>
          <Ul>
            <li>
              <strong>Deletion</strong>: in the App, via Settings &rarr; Delete
              account; on the Site, by written request. We will delete your
              account and associated data within thirty (30) days, subject to
              Section 7 (Data Retention).
            </li>
            <li>
              <strong>Access and portability</strong>: we will provide a copy of
              the personal data we hold about you.
            </li>
            <li>
              <strong>Rectification</strong>: most data is editable within the
              App; for any data that is not, contact us.
            </li>
            <li>
              <strong>Objection to analytics</strong>: we will exclude your
              account from product analytics upon request.
            </li>
          </Ul>
          <P>
            If you are located in California, you have additional rights under
            the California Consumer Privacy Act, including the right not to be
            subjected to discriminatory treatment for exercising your rights. If
            you are located in the European Economic Area or the United Kingdom,
            you have additional rights under the GDPR and the UK GDPR.
          </P>
          <P>
            If you are located in the European Economic Area or the United
            Kingdom and consider that our processing of your personal data
            infringes applicable law, you have the right to lodge a complaint
            with your competent supervisory authority &mdash; in the European
            Economic Area, your national data protection authority; in the United
            Kingdom, the Information Commissioner&apos;s Office. We would,
            however, welcome the opportunity to address your concerns before you
            do so.
          </P>

          <H2 id="security">10. Security</H2>
          <P>
            We implement technical and organisational measures designed to
            protect personal data, including the encryption of data in transit
            between your device and our servers. Our storage providers encrypt
            data at rest and maintain industry-standard security practices. No
            method of transmission or storage can be guaranteed to be entirely
            secure; in the event of a personal data breach affecting you, we will
            notify you and the relevant authorities to the extent required by
            applicable law.
          </P>

          <H2 id="children">11. Children</H2>
          <P>
            The Services are not directed to children under the age of thirteen
            (13), and we do not knowingly collect personal data from such
            children. Where required by applicable law in the European Economic
            Area or the United Kingdom, the minimum age for valid consent to
            information society services may be higher (up to sixteen (16)). If
            you believe that a child has provided us with personal data, please
            contact us and we will delete the relevant account.
          </P>

          <H2 id="changes">12. Changes to this Policy</H2>
          <P>
            We may amend this Policy from time to time. Where we make a material
            change, we will notify you through the Services or by email before
            the change takes effect. The &ldquo;Last updated&rdquo; date at the
            top of this Policy indicates the date of the current version.
          </P>

          <H2 id="contact">13. Contact</H2>
          <P>
            This Policy is issued by Toxome LLC, a limited liability company
            registered in the State of New York. For any matter relating to
            privacy or this Policy, including the exercise of your rights, please
            contact us at <a href="mailto:nyah@toxome.app">nyah@toxome.app</a>.
          </P>

          <Related>
            See also: <Link href="/terms">Terms of Use</Link>.
          </Related>
        </article>
      </main>
      <Footer />
    </>
  );
}

/* ──────────────────────────────────────────────────────────────── */

function Eyebrow({ children }: { children: React.ReactNode }) {
  return (
    <div
      style={{
        fontFamily: "var(--mono)",
        fontSize: 11,
        letterSpacing: "0.14em",
        textTransform: "uppercase",
        color: "var(--ink-3)",
        marginBottom: 14,
      }}
    >
      {children}
    </div>
  );
}

function Title({ children }: { children: React.ReactNode }) {
  return (
    <h1
      style={{
        fontFamily: "var(--sans)",
        fontWeight: 500,
        fontSize: "clamp(36px, 5vw, 56px)",
        lineHeight: 1.05,
        letterSpacing: "-0.025em",
        color: "var(--ink)",
        margin: "0 0 10px",
      }}
    >
      {children}
    </h1>
  );
}

function UpdatedLine({ children }: { children: React.ReactNode }) {
  return (
    <p
      style={{
        fontFamily: "var(--mono)",
        fontSize: 11,
        letterSpacing: "0.08em",
        textTransform: "uppercase",
        color: "var(--ink-3)",
        margin: "0 0 48px",
      }}
    >
      {children}
    </p>
  );
}

function Intro({ children }: { children: React.ReactNode }) {
  return (
    <p
      style={{
        fontSize: 16,
        lineHeight: 1.6,
        color: "var(--ink)",
        letterSpacing: "-0.005em",
        margin: "0 0 24px",
      }}
    >
      {children}
    </p>
  );
}

function H2({ id, children }: { id?: string; children: React.ReactNode }) {
  return (
    <h2
      id={id}
      style={{
        fontFamily: "var(--sans)",
        fontWeight: 600,
        fontSize: 26,
        lineHeight: 1.2,
        letterSpacing: "-0.015em",
        color: "var(--ink)",
        margin: "56px 0 16px",
        scrollMarginTop: 100,
      }}
    >
      {children}
    </h2>
  );
}

function H3({ children }: { children: React.ReactNode }) {
  return (
    <h3
      style={{
        fontFamily: "var(--sans)",
        fontWeight: 500,
        fontSize: 16,
        lineHeight: 1.4,
        letterSpacing: "-0.005em",
        color: "var(--ink)",
        margin: "20px 0 8px",
      }}
    >
      {children}
    </h3>
  );
}

function P({ children }: { children: React.ReactNode }) {
  return (
    <p
      style={{
        fontSize: 16,
        lineHeight: 1.65,
        color: "var(--ink-2)",
        letterSpacing: "-0.005em",
        margin: "0 0 16px",
      }}
    >
      {children}
    </p>
  );
}

function Ul({ children }: { children: React.ReactNode }) {
  return (
    <ul
      style={{
        margin: "0 0 16px",
        paddingLeft: 22,
        color: "var(--ink-2)",
        fontSize: 16,
        lineHeight: 1.65,
        letterSpacing: "-0.005em",
        display: "flex",
        flexDirection: "column",
        gap: 10,
      }}
    >
      {children}
    </ul>
  );
}

function Related({ children }: { children: React.ReactNode }) {
  return (
    <p
      style={{
        marginTop: 72,
        paddingTop: 32,
        fontSize: 14,
        color: "var(--ink-3)",
      }}
    >
      {children}
    </p>
  );
}
